import { NotaContabila, LinieNotaContabila, ContBalanta, MiscareCont, Raport } from './contabilitate-types';

export const noteContabile: NotaContabila[] = [
  {
    id: '1',
    data: '2024-01-15',
    nrNota: 'NC-001',
    tipJurnal: 'Vânzări',
    explicatie: 'Factură client SC Alpha SRL',
    sursa: 'Automat',
    totalDebit: 11900,
    totalCredit: 11900,
  },
  {
    id: '2',
    data: '2024-01-16',
    nrNota: 'NC-002',
    tipJurnal: 'Cumpărări',
    explicatie: 'Factură furnizor Bitum SA',
    sursa: 'Automat',
    totalDebit: 25000,
    totalCredit: 25000,
  },
  {
    id: '3',
    data: '2024-01-17',
    nrNota: 'NC-003',
    tipJurnal: 'Bancă',
    explicatie: 'Încasare client SC Beta SRL',
    sursa: 'Automat',
    totalDebit: 15000,
    totalCredit: 15000,
  },
  {
    id: '4',
    data: '2024-01-18',
    nrNota: 'NC-004',
    tipJurnal: 'Casă',
    explicatie: 'Plată furnizor numerar',
    sursa: 'Manual',
    totalDebit: 2500,
    totalCredit: 2500,
  },
  {
    id: '5',
    data: '2024-01-19',
    nrNota: 'NC-005',
    tipJurnal: 'Diverse',
    explicatie: 'Regularizare stocuri',
    sursa: 'Manual',
    totalDebit: 5000,
    totalCredit: 5000,
  },
];

export const liniiNoteContabile: LinieNotaContabila[] = [
  { id: '1', notaId: '1', cont: '4111', denumireCont: 'Clienți', debit: 11900, credit: 0 },
  { id: '2', notaId: '1', cont: '7015', denumireCont: 'Venituri din vânzare produse', debit: 0, credit: 10000 },
  { id: '3', notaId: '1', cont: '4427', denumireCont: 'TVA colectată', debit: 0, credit: 1900 },
  { id: '4', notaId: '2', cont: '301', denumireCont: 'Materii prime', debit: 21008, credit: 0 },
  { id: '5', notaId: '2', cont: '4426', denumireCont: 'TVA deductibilă', debit: 3992, credit: 0 },
  { id: '6', notaId: '2', cont: '401', denumireCont: 'Furnizori', debit: 0, credit: 25000 },
];

export const balanta: ContBalanta[] = [
  {
    cont: '1012',
    denumire: 'Capital subscris vărsat',
    soldInitialDebit: 0,
    soldInitialCredit: 500000,
    rulajDebit: 0,
    rulajCredit: 0,
    soldFinalDebit: 0,
    soldFinalCredit: 500000,
  },
  {
    cont: '301',
    denumire: 'Materii prime',
    soldInitialDebit: 150000,
    soldInitialCredit: 0,
    rulajDebit: 75000,
    rulajCredit: 45000,
    soldFinalDebit: 180000,
    soldFinalCredit: 0,
  },
  {
    cont: '345',
    denumire: 'Produse finite',
    soldInitialDebit: 200000,
    soldInitialCredit: 0,
    rulajDebit: 120000,
    rulajCredit: 85000,
    soldFinalDebit: 235000,
    soldFinalCredit: 0,
  },
  {
    cont: '401',
    denumire: 'Furnizori',
    soldInitialDebit: 0,
    soldInitialCredit: 85000,
    rulajDebit: 45000,
    rulajCredit: 75000,
    soldFinalDebit: 0,
    soldFinalCredit: 115000,
  },
  {
    cont: '4111',
    denumire: 'Clienți',
    soldInitialDebit: 120000,
    soldInitialCredit: 0,
    rulajDebit: 95000,
    rulajCredit: 65000,
    soldFinalDebit: 150000,
    soldFinalCredit: 0,
  },
  {
    cont: '5121',
    denumire: 'Conturi la bănci în lei',
    soldInitialDebit: 250000,
    soldInitialCredit: 0,
    rulajDebit: 180000,
    rulajCredit: 120000,
    soldFinalDebit: 310000,
    soldFinalCredit: 0,
  },
  {
    cont: '5311',
    denumire: 'Casa în lei',
    soldInitialDebit: 15000,
    soldInitialCredit: 0,
    rulajDebit: 8000,
    rulajCredit: 12000,
    soldFinalDebit: 11000,
    soldFinalCredit: 0,
  },
  {
    cont: '7015',
    denumire: 'Venituri din vânzare produse',
    soldInitialDebit: 0,
    soldInitialCredit: 0,
    rulajDebit: 0,
    rulajCredit: 450000,
    soldFinalDebit: 0,
    soldFinalCredit: 450000,
  },
];

export const miscariCont: Record<string, MiscareCont[]> = {
  '4111': [
    { id: '1', data: '2024-01-05', document: 'FC-001', explicatie: 'Factură client Alpha SRL', debit: 25000, credit: 0, soldDupa: 145000 },
    { id: '2', data: '2024-01-08', document: 'INC-001', explicatie: 'Încasare client Alpha SRL', debit: 0, credit: 15000, soldDupa: 130000 },
    { id: '3', data: '2024-01-12', document: 'FC-002', explicatie: 'Factură client Beta SRL', debit: 35000, credit: 0, soldDupa: 165000 },
    { id: '4', data: '2024-01-15', document: 'FC-003', explicatie: 'Factură client Gamma SRL', debit: 20000, credit: 0, soldDupa: 185000 },
    { id: '5', data: '2024-01-18', document: 'INC-002', explicatie: 'Încasare client Beta SRL', debit: 0, credit: 35000, soldDupa: 150000 },
  ],
  '5121': [
    { id: '1', data: '2024-01-03', document: 'EB-001', explicatie: 'Sold inițial', debit: 250000, credit: 0, soldDupa: 250000 },
    { id: '2', data: '2024-01-08', document: 'INC-001', explicatie: 'Încasare client Alpha SRL', debit: 15000, credit: 0, soldDupa: 265000 },
    { id: '3', data: '2024-01-10', document: 'PL-001', explicatie: 'Plată furnizor Bitum SA', debit: 0, credit: 45000, soldDupa: 220000 },
    { id: '4', data: '2024-01-15', document: 'INC-002', explicatie: 'Încasare client Beta SRL', debit: 35000, credit: 0, soldDupa: 255000 },
    { id: '5', data: '2024-01-20', document: 'PL-002', explicatie: 'Plată salarii', debit: 0, credit: 75000, soldDupa: 180000 },
  ],
};

export const rapoarte: Raport[] = [
  {
    id: '1',
    titlu: 'Profit & Pierdere - Firmă',
    descriere: 'Situația veniturilor și cheltuielilor pe întreaga firmă',
    categorie: 'Profit',
    icon: 'TrendingUp',
  },
  {
    id: '2',
    titlu: 'Profit & Pierdere - Per Produs',
    descriere: 'Analiza profitabilității pe fiecare tip de produs',
    categorie: 'Profit',
    icon: 'Package',
  },
  {
    id: '3',
    titlu: 'Profit & Pierdere - Per Stație',
    descriere: 'Rezultate financiare pe stație de producție',
    categorie: 'Profit',
    icon: 'Factory',
  },
  {
    id: '4',
    titlu: 'Cashflow 30 zile',
    descriere: 'Prognoza fluxului de numerar pentru următoarele 30 zile',
    categorie: 'Cashflow',
    icon: 'Calendar',
  },
  {
    id: '5',
    titlu: 'Cashflow 60 zile',
    descriere: 'Prognoza fluxului de numerar pentru următoarele 60 zile',
    categorie: 'Cashflow',
    icon: 'CalendarDays',
  },
  {
    id: '6',
    titlu: 'Cashflow 90 zile',
    descriere: 'Prognoza fluxului de numerar pentru următoarele 90 zile',
    categorie: 'Cashflow',
    icon: 'CalendarRange',
  },
  {
    id: '7',
    titlu: 'Marjă pe Produs',
    descriere: 'Analiza marjei de profit per tip de produs finit',
    categorie: 'Marjă',
    icon: 'BarChart3',
  },
  {
    id: '8',
    titlu: 'Marjă pe Client',
    descriere: 'Analiza marjei de profit per client',
    categorie: 'Marjă',
    icon: 'Users',
  },
  {
    id: '9',
    titlu: 'Situație Solduri Clienți',
    descriere: 'Sinteză solduri și încasări clienți',
    categorie: 'Solduri',
    icon: 'UserCheck',
  },
  {
    id: '10',
    titlu: 'Situație Solduri Furnizori',
    descriere: 'Sinteză solduri și plăți furnizori',
    categorie: 'Solduri',
    icon: 'Truck',
  },
];
